version: "3.8"

services:

    redis:
        image: redis:alpine
        container_name: redis

    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER= postgres
            - POSTGRES_PASSWORD=postgres

        container_name: postgres_db

    app:
        build: .
        volumes:
            - .:/django
        ports:
            - 8000:8000
        image: app:core
        container_name: core_app
        command: python3 manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
  
    celery:
        restart: always
        build: 
            context: .
        command: celery -A core worker -1 DEBUG
        volumes:
            - .:/django
        container_name: celery
        depends_on:
            - db
            - redis
            - app






 